### ISSUE TITLE
Colour issues when choosing Light theme for code snippets

### ISSUE THREAD

**Issue by bclozel** [spring-io/spring-doc-resources#14]
As suggested by several community members (for example, [here](https://twitter.com/jbnizet/status/1097541918752415744)), I'd like to move to a light theme for code snippets by default. I personally like the dark ones very much, but it's apparently not friendly to people with colour vision issues.

I've tried using the `github` theme (provided by spring-doc-resources) and I'm seeing the following.

<img width="1269" alt="Screenshot 2019-05-13 at 17 17 01" src="https://user-images.githubusercontent.com/103264/57633501-fb6f3880-75a3-11e9-83a8-c51e1f294a24.png">

Is there something we can do to make things work with both light and dark themes? If not, I think we should default on a light one.

**Comment by odrotbohm** [comment]
This changes breaks the code highlighting for projects that use the `atom-one-dark-reasonable` highlight.js theme as [suggested in the readme](https://github.com/spring-io/spring-doc-resources/blob/master/README.md).
