### ISSUE TITLE
Can this be used for third party projects?

### ISSUE THREAD

**Issue by AlexCzar** [spring-io/spring-doc-resources#20]
I'm trying to use this to generate documentation for my own project, but I fail at properly configuring it. Is this supposed to be used as part of internal spring projects build, or is this supposed to be for general use?
The problems I have with this project do not look like problems a GA software from Spring could have.

**Comment by bclozel** [comment]
This is built for the needs of the Spring team first and offers no guarantee of support or customization.
There might be hard-coded values that don't make sense for non-Spring projects. This is also why we're not distributing this artifact on maven central, but only on our milestone repository.

This is open source still, so you're free to use it in your own projects.
Feel free to create issues and PRs for specific problems, but keep in mind we're not as committed as other Spring projects with official support.

Thanks!
