### ISSUE TITLE
Include additional highlight.js themes

### ISSUE THREAD

**Issue by sbrannen** [spring-io/spring-doc-resources#25]
I noticed that `spring-docs-resources` includes a limited set of themes supported by highlight.js.

In Spring Framework, we are considering switching to one of the themes available [here](https://github.com/highlightjs/highlight.js/tree/master/src/styles) -- for example, the `googlecode` theme.

What is the process for getting support for additional themes?

Shall we just request that they are added to the published archive?

If not, what is the recommended approach for making them available to the published documentation?

FYI: I know that I can download the CSS files, check them into version control, and then copy them manually in the build process to the output directory for Asciidoctor, but I'm wondering if you plan to provide official support for other themes.

**Comment by bclozel** [comment]
We've added the googlecode stylesheet in #40.
As for other themes, we can add them on-demand as long as they're light variants and they'll match with our current style.

**Comment by sbrannen** [comment]
Thanks, @bclozel! 👍 

Do you know when 0.2.1 is planned for release?

I'm asking because of https://github.com/spring-projects/spring-framework/issues/24865.

**Comment by bclozel** [comment]
@sbrannen 0.2.1.RELEASE has been published!

**Comment by sbrannen** [comment]
The `googlecode.css` file added to 0.2.1.RELEASE unfortunately cannot be used with the `highlightjs-theme` since those file names have to contain `.min` before the `.css` suffix.

The `.min` requirement is documented in the [Asciidoctor reference](https://asciidoctor.org/docs/user-manual/#highlight-js).

As a test for https://github.com/spring-projects/spring-framework/issues/24865, I renamed the file to `googlecode.min.css` after the `spring-doc-resources.zip` archive had been unpacked, and that worked.

So, please reopen this issue to rename the file to `googlecode.min.css`.

Similarly, the `github-gist.css` would need to be renamed to `github-gist.min.css` if it's intended to be used as a `highlightjs-theme`.

**Comment by bclozel** [comment]
@sbrannen this has been fixed in #42

**Comment by sbrannen** [comment]
Thanks, @bclozel!

Looking forward to 0.2.2.
