### ISSUE TITLE
Too large line width on large screens

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/spring-doc-resources#30]
[This commit](https://github.com/spring-io/spring-doc-resources/commit/ec67c149ff5ac37d7956e43fc559b03ceaf2722d) has caused the content to be spread out much more on large screen widths.

Before:
![Bildschirmfoto 2020-02-02 um 14 03 46](https://user-images.githubusercontent.com/128577/73608577-10be4400-45c5-11ea-930d-f96187ec74cf.png)

After:
![Bildschirmfoto 2020-02-02 um 14 02 03](https://user-images.githubusercontent.com/128577/73608581-161b8e80-45c5-11ea-9672-6cccb22abbcb.png)

I'd argue the former was much more readable as it's hard for the eye to find the next line when reaching the end of a line in the new layout. Readability studies suggest that floating text should not exceed a certain line length and it feels like we've gone too far here.

**Comment by oodamien** [comment]
@here Are we sure about this change?
We pushed this changes following feedbacks (adaptation for large screen).

**Comment by mminella** [comment]
Nothing else on the spring.io site expands to full width on extra wide monitors.  I don't think I'd expect the docs to either in that case...

**Comment by odrotbohm** [comment]
The actual issue is not about using as much screen estate as possible but rather that text becomes harder to read if the eye cannot easily connect to the next line when reaching the end of the former.

Most scientific studies I am aware of seem to end up at lengths of ~95cpl which we already exceeded with the previous setting. Here’s [an example](http://web.archive.org/web/20170918212943/http://psychology.wichita.edu/surl/usabilitynews/72/LineLength.asp).

**Comment by Buzzardo** [comment]
Thanks, Brian. Now we can pick up that version. :)
