### ISSUE TITLE
Styling for Code that is also a Link

### ISSUE THREAD

**Issue by rwinch** [spring-io/spring-doc-resources#32]
It would be nice to update the styling so that code that is also a link is obvious. An example is the following asciidoctor source:

```
https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/SecurityFilterChain.html[`SecurityFilterChain`] is used by <<servlet-filterchainproxy>> to determine which Spring Security ``Filter``s should be invoked for this request.
```

This outputs HTML that is styled like this:

![image](https://user-images.githubusercontent.com/362503/74749266-836b2880-522f-11ea-87d2-13fcc86bd463.png)

The first `SecurityFilterChain` is a link (but it is not obvious), `FilterChainProxy` is a link (this seems obvious by the styling), and ``Filter``s is not a link. Due to the fact that `SecurityFilterChain` does not have anything to distinguish it from ``Filter``s, it is surprising that `SecurityFilterChain` is a link.

I think it would be nice if we updated the styling so that it is obvious that `SecurityFilterChain` is a link.

**NOTE:** Hovering over `SecurityFilterChain` does show an underline which helps to indicate it is a link, but this is only after the user decides to hover over the text. 

Another thing that I find interesting is that code that is a link within a list has the color changed. See https://github.com/spring-io/spring-doc-resources/blob/db7ca7c88b4ab0b8707e1112daadf3d3e6a720cb/src/main/sass/spring/_asciidoctor.scss#L1647

**Comment by bclozel** [comment]
Closed with f61069a

**Comment by rwinch** [comment]
Thanks @bclozel! Any idea when a release will be out?

**Comment by bclozel** [comment]
@rwinch this has been fixed while completely changing the documentation style (to get in line with the new spring.io website). We'd like to cut a release soon. If you get a chance to test our `0.2.0.BUILD-SNAPSHOT` version, we would be more confident releasing it!

**Comment by rwinch** [comment]
Thanks for the response @bclozel. Overall I like the new styling. It certainly does look like it belongs on the refreshed spring.io site.

I struggle a bit with the differences between code that is a link and that isn't. Now the code that isn't a link looks to me like a link that was previously clicked on (it is a blueish-purple). Here is a screenshot:

![image](https://user-images.githubusercontent.com/362503/75785252-0f4d7c00-5d29-11ea-8a36-fab82f0abd15.png)

In this case `ProviderManager` is a link and `AuthenticationProvider` is not. To me it looks like both of them are links. Perhaps there is something that could be done to ensure that code that isn't a link looks distinct from links?

I've also attached all of the security reference so you can take a look for yourself what the result is.

[spring-security-reference.zip](https://github.com/spring-io/spring-doc-resources/files/4281793/spring-security-reference.zip)

**Comment by bclozel** [comment]
What do you think @oodamien ? I don't know if there's a way to improve the situation here.
