### ISSUE TITLE
When we use a code wrapping in the heading it loses its heading meaning and present as plain code with small text

### ISSUE THREAD

**Issue by artembilan** [spring-io/spring-doc-resources#45]
The previous version:

![image](https://user-images.githubusercontent.com/1071590/80737963-4f8b6980-8ae2-11ea-8e9d-f7a7728791a6.png)

Current one:

![image](https://user-images.githubusercontent.com/1071590/80738017-5f0ab280-8ae2-11ea-801f-a3366c2bbdb5.png)

It becomes more obvious when we don't use any plain text in the heading at all:

![image](https://user-images.githubusercontent.com/1071590/80738115-7fd30800-8ae2-11ea-957a-81187495d693.png)

Pay attention to the `ReactiveMessageHandler` and `ReactiveMessageSourceProducer`. They are headings and I was lost looking for them in big bold text.

Thanks

**Comment by Buzzardo** [comment]
When we mark code in a heading, it needs to be clear that it's both code and a heading. I think the solution would be to lose the box and make it bold but keep the code font.

What do you think, @oodamien?
