### ISSUE TITLE
Fix snapshot version identifier format

### ISSUE THREAD

**Issue by mp911de** [spring-io/spring-doc-resources#5]
The version is `0.1.0-BUILD-SNAPSHOT` but should rather be `0.1.0.BUILD-SNAPSHOT` (note the dot between `0` and `BUILD…`).

**Comment by bclozel** [comment]
Thanks!

**Comment by bclozel** [comment]
As an FYI @oodamien and @Buzzardo , you should use now use `0.1.0.BUILD-SNAPSHOT` when depending on this project.
