### ISSUE TITLE
Short tables look bad

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-doc-resources#51]
Old

![Screen Shot 2020-10-01 at 10 02 20 AM](https://user-images.githubusercontent.com/519772/94840400-39edd900-03cd-11eb-8b98-0719972f78e4.png)

Current

![Screen Shot 2020-10-01 at 10 02 26 AM](https://user-images.githubusercontent.com/519772/94840408-3c503300-03cd-11eb-8f9b-63b7da3714b8.png)

**Comment by philwebb** [comment]
I think this is due to the fix for #34

**Comment by brenuart** [comment]
I'm not a CSS expert at all, but here is what we added to temporarily fix the issue:

```
table.tableblock {
  display: table;
}
```

Not saying this how the issue must be fixed... but at least it seems to have solved it on our side.

**Comment by bclozel** [comment]
@brenuart As pointed out by Phil, doing so will break #34.

Here is the sample document with the change you're suggesting:

![image](https://user-images.githubusercontent.com/103264/97917258-82920c80-1d54-11eb-972f-0037e66e068e.png)

**Comment by philwebb** [comment]
I think this has been solved with https://github.com/spring-io/asciidoctor-spring-backends
