### ISSUE TITLE
Artifact Retrieval Issues

### ISSUE THREAD

**Issue by pluttrell** [spring-io/spring-doc-resources#73]
We generate docs like Spring for several projects using this repo. It works quite well. Our build scripts look just like the example provided in the README.

We've been pulling `io.spring.docresources:spring-doc-resources:0.2.5@zip` from `https://repo.spring.io/release` like this:

```
repositories {
    maven {
        url 'https://repo.spring.io/release'
    }
}
dependencies {
    docs "io.spring.docresources:spring-doc-resources:0.2.5@zip"
}
```

But sometime between May 10, 2023 and June 8, 2023 we started to see the following error when we try to pull the dependency:

```
* What went wrong:
Could not determine the dependencies of task ':something-docs:prepareAsciidocBuild'.
> Could not resolve all files for configuration ':something-docs:docs'.
   > Could not resolve io.spring.docresources:spring-doc-resources:0.2.5.
     Required by:
         project :something-docs
      > Could not resolve io.spring.docresources:spring-doc-resources:0.2.5.
         > Could not get resource 'https://repo.spring.io/release/io/spring/docresources/spring-doc-resources/0.2.5/spring-doc-resources-0.2.5.pom'.
            > Could not GET 'https://repo.spring.io/release/io/spring/docresources/spring-doc-resources/0.2.5/spring-doc-resources-0.2.5.pom'. Received status code 401 from server: 


```

When I looked at https://repo.spring.io/release, it appears that there's no long an `io` package.

Where might we be able to find the published artifacts?

Thanks!

**Comment by bclozel** [comment]
Duplicates #71
